licensing.agent.server.url=http://localhost:8082/licensing-agent
licensing.agent.server.app.user=licensingAgentUser
licensing.agent.server.app.pass=licensingAgentPass
licensing.agent.api.path=/v1/licenses/access
licensing.agent.http.connect-timeout-seconds=40
licensing.agent.http.response-timeout-seconds=40
licensing.agent.http.retries=3
licensing.agent.http.retry-interval-seconds=3
