coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        enabled: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "**/target/**"
  - "**/generated/**"
  - "**/generated-sources/**"

flags:
  license-generator:
    paths:
      - "license-generator/"
  licensing-service:
    paths:
      - "licensing-service/"
  licensing-service-client:
    paths:
      - "licensing-service-client/"
  licensing-agent:
    paths:
      - "licensing-agent/"
  licensing-agent-cli:
    paths:
      - "licensing-agent-cli/"