package com.c9.licensing.model;

public enum LicenseErrorCode {
	LICENSE_INVALID, LICENSE_EXPIRED, LICENSE_INACTIVE, LICENSE_USAGE_LIMIT_EXCEEDED, UNKNOWN_ERROR, TOKEN_EXPIRED,
	TOKEN_INVALID, TOKEN_INVALID_ACCESS, TOKEN_REFRESHED, INVALID_REQUEST_PARAM, TOKEN_ALREADY_EXIST
}