package com.c9.licensing.model;

public enum LicenseServiceStatus {
	LICENSE_INVALID, LICENSE_EXPIRED, LICENSE_INACTIVE, LICENSE_USAGE_LIMIT_EXCEEDED, 
	LICENSE_SERVICE_ID_NOT_SUPPORTED, LICENSE_INVALID_SERVICE_ID,LICENSE_SERVICE_INVALID_CHECKSUM,LICENSE_SERVICE_VERSION_NOT_SUPPORTED,
	TOKEN_CREATED,TOKEN_EXPIRED, TOKEN_INVALID, TOKEN_INVALID_ACCESS, TOKEN_REFRESHED, TOKEN_ALREADY_EXIST, 
	TOKEN_ACTIVE, TOKEN_IS_TOO_OLD_FOR_REFRESH, INVALID_PARAMETER, MISSING_PARAMETER, UNKNOWN_ERROR
}