server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /licensing-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: licensing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:RedBar9182_}
      timeout: 5s
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 5s


cache:
  default-spec:
    ttl-minutes: 10
  caches:
    userInfo:
      ttl-minutes: 60
      type: io.github.bsayli.licensing.domain.model.LicenseInfo
    userOfflineInfo:
      ttl-minutes: 1440    # 24h (offline fallback)
      type: io.github.bsayli.licensing.domain.model.LicenseInfo
    activeClients:
      ttl-minutes: 93      # = 90 (exp) + 2 (jitter) + 1 (grace)
      type: io.github.bsayli.licensing.domain.model.ClientSessionSnapshot

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    io.github.bsayli.licensing: DEBUG

licensing:
  api:
    basic:
      username: "licensingUser"
      password: "licensingPass"
      realm: "LicensingService"

app:
  openapi:
    version: @project.version@
    base-url: "http://localhost:${server.port}${server.servlet.context-path:}"

license:
  jwt:
    private:
      key: 'MC4CAQAwBQYDK2VwBCIEIKuiaWNlW28cRkwTVEMvyruAEF/jZomZw0M6GnIXEg5B'
    public:
      key: 'MCowBQYDK2VwAyEA7Of0J8DCzgMz1dhqubVrCx6SfiZT6tsULQx2MnJ9Wbw='
  service:
    ids: [ crm, billing, reporting ]
    checksum-required: [ crm, billing, reporting ]

userid:
  secret:
    key: '2u3mWVT8QJEyreemcKchXBJu7FRipIztJ76DBHlyhT8='

signature:
  public:
    key: 'MCowBQYDK2VwAyEAyHQ5vPg4ukYWGR/sCLKLAzyQLzhszsX5SLNbJ6XeJBw='

keycloak:
  server-url: http://localhost:8180
  realm: licensing-realm
  client-id: licensing-service-client
  client-secret: 'lXY1tKNmHGnzYXGH35TDYdb5nXCmPgLF'
  timeout: 10
  pool:
    max-total: 10
    max-per-route: 5

retry:
  user-service:
    max-attempts: 2
    initial-delay: 1000      # ms
    multiplier: 2
    max-delay: 8000          # ms
  user-service-async:
    max-attempts: 3
    initial-delay: 2000      # ms
    multiplier: 2
    max-delay: 15000         # ms

jwt:
  token:
    expiration: 90m
    max:
      jitter: 2m

async:
  pool:
    core: 4
    max: 8
    queue: 100
    threadNamePrefix: "LicenseService-"