server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /licensing-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: licensing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    io.github.bsayli.licensing: DEBUG

licensing:
  api:
    basic:
      username: "licensingUser"
      password: "licensingPass"
      realm: "LicensingService"

app:
  openapi:
    base-url: "http://localhost:${server.port}${server.servlet.context-path:}"

license:
  jwt:
    private:
      key: 'MFECAQEwBQYDK2VwBCIEIJa52B/FN/sjW/nlB9Id+Na2B8rI2+5ZPhXTIQSzH+3BgSEA6lNvY1+qsRSYgo66OFxWZxQymd2wC6LYNr1+q2gHHMo='
    public:
      key: 'MCowBQYDK2VwAyEA6lNvY1+qsRSYgo66OFxWZxQymd2wC6LYNr1+q2gHHMo='
  service:
    ids: [ crm, billing, reporting ]
    checksum-required: [ crm, billing, reporting ]

userid:
  secret:
    key: 's/PUyV6Ym/v0A+HehYFZ9GTpatSL1MkcVW1zBLf3cX4='

signature:
  public:
    key: 'MCowBQYDK2VwAyEAl/bnQXUbWqDOZYxCBd0mQ2JejBUWNteKhfC2zPS+GME='

keycloak:
  server-url: http://localhost:8180
  realm: licensing-realm
  client-id: licensing-service-client
  client-secret: 'lXY1tKNmHGnzYXGH35TDYdb5nXCmPgLF'
  timeout: 10
  pool:
    max-total: 10
    max-per-route: 5

retry:
  user-service:
    max-attempts: 2
    initial-delay: 1000      # ms
    multiplier: 2
    max-delay: 8000          # ms
  user-service-async:
    max-attempts: 3
    initial-delay: 2000      # ms
    multiplier: 2
    max-delay: 15000         # ms

jwt:
  token:
    expiration: 60m         # 60 minutes for demo
    max:
      jitter: 2m            # renewal tolerance (maximum)

caching:
  spring:
    clientLicenseInfoTTL: 1h                  # online cache
    clientLicenseInfoOffLineSupportTTL: 24h   # offline cache (long-lived)

async:
  pool:
    core: 4
    max: 8
    queue: 100
    threadNamePrefix: "LicenseService-"