server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /licensing-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: licensing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    io.github.bsayli.licensing: DEBUG

app:
  openapi:
    base-url: "http://localhost:${server.port}${server.servlet.context-path:}"
  user: 'c9License'
  pass: 'aPJ829Lrp15'

license:
  secret:
    key: 'SEYhWGm3FwD7g7iXESuM+LuaNgnDtEL5S5HS4td7+SA='
  jwt:
    private:
      key: 'MFECAQEwBQYDK2VwBCIEIJa52B/FN/sjW/nlB9Id+Na2B8rI2+5ZPhXTIQSzH+3BgSEA6lNvY1+qsRSYgo66OFxWZxQymd2wC6LYNr1+q2gHHMo='
    public:
      key: 'MCowBQYDK2VwAyEA6lNvY1+qsRSYgo66OFxWZxQymd2wC6LYNr1+q2gHHMo='
  service:
    ids: [ crm, billing, reporting ]
    checksum-required: [ crm, billing, reporting ]

userid:
  secret:
    key: 's/PUyV6Ym/v0A+HehYFZ9GTpatSL1MkcVW1zBLf3cX4='

signature:
  public:
    key: 'MIIDQjCCAjUGByqGSM44BAEwggIoAoIBAQCPeTXZuarpv6vtiHrPSVG28y7FnjuvNxjo6sSWHz79NgbnQ1GpxBgzObgJ58KuHFObp0dbhdARrbi0eYd1SYRpXKwOjxSzNggooi/6JxEKPWKpk0U0CaD+aWxGWPhL3SCBnDcJoBBXsZWtzQAjPbpUhLYpH51kjviDRIZ3l5zsBLQ0pqwudemYXeI9sCkvwRGMn/qdgYHnM423krcw17njSVkvaAmYchU5Feo9a4tGU8YzRY+AOzKkwuDycpAlbk4/ijsIOKHEUOThjBopo33fXqFD3ktm/wSQPtXPFiPhWNSHxgjpfyEc2B3KI8tuOAdl+CLjQr5ITAV2OTlgHNZnAh0AuvaWpoV499/e5/pnyXfHhe8ysjO65YDAvNVpXQKCAQAWplxYIEhQcE51AqOXVwQNNNo6NHjBVNTkpcAtJC7gT5bmHkvQkEq9rI837rHgnzGC0jyQQ8tkL4gAQWDt+coJsyB2p5wypifyRz6Rh5uixOdEvSCBVEy1W4AsNo0fqD7UielOD6BojjJCilx4xHjGjQUntxyaOrsLC+EsRGiWOefTznTbEBplqiuH9kxoJts+xy9LVZmDS7TtsC98kOmkltOlXVNb6/xF1PYZ9j897buHOSXC8iTgdzEpbaiH7B5HSPh++1/et1SEMWsiMt7lU92vAhErDR8C2jCXMiT+J67ai51LKSLZuovjntnhA6Y8UoELxoi34u1DFuHvF9veA4IBBQACggEAUzTk7qzLnma3DAie/xgibOjNEXFh4ThLOB67Lk0MLs3wkM9giGQRKiwHqdlQLF9ICOZdjti2pp0saQE7W6poXIq03OV46cfvSsbMzAT4OihWJI2UOlQqnbWkn4gHRpgXndPlKKTJ7jNsBy2OAE8B4FCfE74xkjjMqB7qwGAl1vGtRMu2XMKPN/+Aa5WyEv7k9cgv7QjUfDrn6tvutWEnMNm4ZdR3zQV4+wjNHzcJ5+l7BqCY/y6lvUQ/wB6rC6Whq4FNpjjBrZreekoLZbTNUceOd+OnEPeUCDxcG38m/1yNTfV0CBCWDzJ2zl383m6vCQq0asq5Vo2cBp+pA72/gw=='

keycloak:
  server-url: http://localhost:8180
  realm: licensing-realm
  client-id: licensing-service-client
  client-secret: 'lXY1tKNmHGnzYXGH35TDYdb5nXCmPgLF'
  timeout: 10
  pool:
    max-total: 10
    max-per-route: 5

retry:
  userService:
    maxAttempts: 3
    initialDelay: 5000
    multiplier: 2
    maxDelay: 30000
  userServiceAsync:
    maxAttempts: 4
    initialDelay: 10000
    multiplier: 3
    maxDelay: 360000

jwt:
  token:
    expiration: 120           # minutes
    max:
      jitter: 300000          # milliseconds

caching:
  spring:
    clientLicenseInfoTTL: 2                 # hours
    clientLicenseInfoOffLineSupportTTL: 120 # hours