package com.c9.licensing.sdk.model;

public enum LicenseStatus {
	LICENSE_ACTIVE, LICENSE_INVALID, LICENSE_EXPIRED, LICENSE_INACTIVE, LICENSE_USAGE_LIMIT_EXCEEDED, 
	LICENSE_SERVICE_ID_NOT_SUPPORTED, LICENSE_INVALID_SERVICE_ID,LICENSE_SERVICE_INVALID_CHECKSUM,LICENSE_SERVICE_VERSION_NOT_SUPPORTED,
	SIGNATURE_INVALID, INVALID_PARAMETER, MISSING_PARAMETER, INVALID_REQUEST, UNKNOWN_ERROR
}