server:
  port: ${APP_PORT:8082}
  servlet:
    context-path: /licensing-service-sdk
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: licensing-service-sdk
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    io.github.bsayli.licensing.sdk: DEBUG

caching:
  spring:
    licenseTokenTTL: 90m

licensing:
  sdk:
    api:
      basic:
        username: "licensingSdkUser"
        password: "licensingSdkPass"
        realm: "LicensingServiceSDK"

app:
  openapi:
    base-url: "http://localhost:${server.port}${server.servlet.context-path:}"

licensing-service-api:
  base-url: "http://localhost:8081/licensing-service"
  basic:
    username: "licensingUser"
    password: "licensingPass"
  connect-timeout-seconds: 10
  connection-request-timeout-seconds: 10
  read-timeout-seconds: 15

  max-connections-total: 64
  max-connections-per-route: 16

signature:
  private:
    key: "MC4CAQAwBQYDK2VwBCIEIG265cW0Yrh583IXT/Hmfd2A1hFnHXViCZHpJu83OBFj"