package com.c9.licensing.sdk.model.server;

public enum LicenseServerServiceStatus {
	LICENSE_INVALID, LICENSE_EXPIRED, LICENSE_INACTIVE, LICENSE_USAGE_LIMIT_EXCEEDED, 
	LICENSE_SERVICE_ID_NOT_SUPPORTED, LICENSE_INVALID_SERVICE_ID,LICENSE_SERVICE_INVALID_CHECKSUM,LICENSE_SERVICE_VERSION_NOT_SUPPORTED,
	TOKEN_CREATED,TOKEN_EXPIRED, TOKEN_INVALID, TOKEN_INVALID_ACCESS, TOKEN_REFRESHED, TOKEN_ALREADY_EXIST, 
	TOKEN_ACTIVE, TOKEN_IS_TOO_OLD_FOR_REFRESH, SIGNATURE_INVALID, INVALID_PARAMETER, MISSING_PARAMETER,
	INVALID_REQUEST, INTERNAL_SERVER_ERROR, UNKNOWN_ERROR
}