networks:
  license_network:
    external: true

services:
  licensing-agent-cli:
    build: ./../../licensing-agent-cli
    image: licensing-agent-cli:2.0.0
    container_name: licensing-agent-cli
    networks:
      - license_network
    environment:
      LICENSE_AGENT_URL: "http://licensing-agent:8082/licensing-agent"
      INSTANCE_ID: "licensing-service~demo~00:11:22:33:44:55"
      SERVICE_ID: "crm"
      SERVICE_VERSION: "1.5.0"
      LICENSE_KEY: "BSAYLI~X66e_qYlfPxWiIaN2ahPb9tQFyqjMuTih06LCytzjZ0~0aT6lLTZGkO1zHHPHFDzwF7zPiZLRLWSl06HSVQO5z+NqtzzcFCUkkVFuqHTYKcAcI9037sQQQSfBQakQDUoCA=="
    restart: "no"