networks:
  license_network:
    external: true

services:
  licensing-service-sdk-cli:
    build: ./../../licensing-service-sdk-cli
    image: licensing-service-sdk-cli:1.0.5
    container_name: licensing-service-sdk-cli
    networks:
      - license_network
    environment:
      LICENSE_SERVICE_SDK_URL: "http://licensing-service-sdk:8082/licensing-service-sdk"
      INSTANCE_ID: "licensing-service~demo~00:11:22:33:44:55"
      SERVICE_ID: "crm"
      SERVICE_VERSION: "1.5.0"
      LICENSE_KEY: "BSAYLI.AQA3-gCQ66DQsfC0LwnAO8DTjKgad7DhPaOtCf7WG2bFUoK9pmScIhhCf2S-D0j8g4jC7nlFrLDpuM0ezEoDQc79SizxxEIUGN9YUhTNBW7iRQ"
    restart: "no"